### ISSUE TITLE
Chrome Dev Editor not workin. 

### ISSUE THREAD

**Issue by RoshanLakmal** [GoogleChrome/chromedeveditor#4096]
Chrome Dev Editor is not working in the latest Chrome update version.
Version 64.0.3282.140(Official Build) (64-bit) both Windows as well as Mac.

**Comment by bigriff** [comment]
Stopped working in Chrome OS as well, 64.0.3282.190. 

When you open the app, does it just show spin icon?

**Comment by gio1135** [comment]
Yes

**Comment by RoshanLakmal** [comment]
I used a old chrome version and it works fine. I think the latest update some how crashed something.

**Comment by rafi16jan** [comment]
Chrome Dev Editor is my favorite Code Editor on Chrome OS. There are plenty of Javascript Apps that I've been develop with it. Sad it's not working anymore :(

**Comment by RoshanLakmal** [comment]
Is there anyway we can patch this issue ?

**Comment by rafi16jan** [comment]
I'm trying to get the log but I can't figure it where does it stored. Seems /var/log only shows android apps logs

**Comment by nmcain** [comment]
I have taken it upon myself to fix this issue because I love this app and do not want it to see the same fate as arc welder

**Comment by gio1135** [comment]
@nmcain Yeah, ARC Welder was amazing when it came out. It's a shame that it's no longer with us.

**Comment by rafi16jan** [comment]
@nmcain do you find a fix though?

There's actually a good alternative called Quantum https://chrome.google.com/webstore/detail/quantum/hmnlklahndgbhdoclhdnoafhafbhmnkm

**Comment by nmcain** [comment]
I found a fix: I removed the code for the loading screen because the chrome update removed the function where the loader goes away when the page is done loading.

**Comment by YaserAlOsh** [comment]
@nmcain Nice, could you point to us where the loading screen code is? Thanks

**Comment by RoshanLakmal** [comment]
@nmcain  Well done yes please tell us where we need to do the change?

**Comment by nmcain** [comment]
I assume it is in the spark.dart file, but is there any way to contact the
original developers?

**Comment by darthwalsh** [comment]
@rafi16jan Quantum looks cool, but it's ChromeOS only? I'd like to use the same IDE on all my development platforms...

**Comment by darthwalsh** [comment]
@nmcain  Nice find! The Google Archive account says "All projects here are completely frozen, though feel free to fork and continue using them on your own."

Want to create a fork that removes the loading screen code?

**Comment by ghost** [comment]
I wonder if the code can be used to make a decent Flutter based IDE.
This would run on all desktops, Chrome and even mobiles.

https://github.com/google/flutter-desktop-embedding

**Comment by MyrmidonGit** [comment]
I understand that this thread is almost two months old, but it's still open, and I don't see a definitive solution.

So.. I'm pretty naive when it comes to big projects like this.. I understand most code languages, and I'd love to be able to use Chrome Dev Editor. I've read through this thread a few times, as well as the spark.dart file as @nmcain mentioned, but I can't seem to find the correct portion of the code to delete or edit in order to remove the loading screen, which is what the majority of this thread seemed to accept as the solution. However @darthwalsh also mentioned it may be a good idea to create a fork that removes the loading screen code. If that exists, then a simple link to the fork would be great to see.

Best Regards - Richie

**Comment by Noisytoot** [comment]
# I also have the issue.
## The DevTools Log shows:
```
spark_polymer.html:363 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource: 'wasm-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-zszB8rWNmzzEpQZ4kDLMJXlSIzMDfBnWIaDamOW5/dk='), or a nonce ('nonce-...') is required to enable inline execution.

[Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile.It is now effectively no-op, acting as if it were a descendant combinator. /deep/ combinator will be removed, and will be invalid at M65. You should remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.
spark_polymer.html_bootstrap.dart.js:69258 Uncaught DOMException: Failed to execute 'createShadowRoot' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
    at SparkSelector.dart.Element.createShadowRoot$0 (chrome-extension://pnoffddplpippgcfjdhbmhkofpnaalpg/spark_polymer.html_bootstrap.dart.js:116085:79)
    at SparkSelector.dart.Polymer.shadowFromTemplate$1 (chrome-extension://pnoffddplpippgcfjdhbmhkofpnaalpg/spark_polymer.html_bootstrap.dart.js:144836:21)
    at SparkSelector.dart.Polymer.parseDeclaration$1 (chrome-extension://pnoffddplpippgcfjdhbmhkofpnaalpg/spark_polymer.html_bootstrap.dart.js:144807:23)
    at SparkSelector.dart.Polymer.parseDeclarations$1 (chrome-extension://pnoffddplpippgcfjdhbmhkofpnaalpg/spark_polymer.html_bootstrap.dart.js:144799:16)
    at SparkSelector.dart.Polymer._makeElementReady$0 (chrome-extension://pnoffddplpippgcfjdhbmhkofpnaalpg/spark_polymer.html_bootstrap.dart.js:144774:14)
    at SparkSelector.dart.Polymer.bindFinished$0 (chrome-extension://pnoffddplpippgcfjdhbmhkofpnaalpg/spark_polymer.html_bootstrap.dart.js:144961:21)
    at Object._processBindings (chrome-extension://pnoffddplpippgcfjdhbmhkofpnaalpg/spark_polymer.html_bootstrap.dart.js:188332:10)
    at Object._cloneAndBindInstance (chrome-extension://pnoffddplpippgcfjdhbmhkofpnaalpg/spark_polymer.html_bootstrap.dart.js:188135:9)
    at Object._cloneAndBindInstance (chrome-extension://pnoffddplpippgcfjdhbmhkofpnaalpg/spark_polymer.html_bootstrap.dart.js:188129:11)
    at TemplateBindExtension.createInstance$2 (chrome-extension://pnoffddplpippgcfjdhbmhkofpnaalpg/spark_polymer.html_bootstrap.dart.js:188655:21)
spark_polymer.html_bootstrap.dart.js:155107 UnknownJsTypeError
_handleUncaughtException @ spark_polymer.html_bootstrap.dart.js:155107
spark_polymer.html_bootstrap.dart.js:155112 TypeError: Cannot set property 'textContent' of null
    at KeyBindingManager._updateName$1 (spark_polymer.html_bootstrap.dart.js:160839)
    at SparkPolymer.initAceManager$0 (spark_polymer.html_bootstrap.dart.js:155232)
    at Spark_init___closure.dart.Spark_init___closure.call$1 (spark_polymer.html_bootstrap.dart.js:155864)
    at StaticClosure.dart._rootRunUnary (spark_polymer.html_bootstrap.dart.js:103971)
    at _CustomZone.dart._CustomZone.runUnary$2 (spark_polymer.html_bootstrap.dart.js:107323)
    at _Future__propagateToListeners_handleValueCallback.call$0 (spark_polymer.html_bootstrap.dart.js:104966)
    at Object._Future__propagateToListeners (spark_polymer.html_bootstrap.dart.js:104873)
    at _Future._completeWithValue$1 (spark_polymer.html_bootstrap.dart.js:104757)
    at _Future__asyncComplete_closure0.dart._Future__asyncComplete_closure0.call$0 (spark_polymer.html_bootstrap.dart.js:104952)
    at StaticClosure.dart._rootRun (spark_polymer.html_bootstrap.dart.js:103962)
_handleUncaughtException @ spark_polymer.html_bootstrap.dart.js:155112
The source list for Content Security Policy directive 'script-src' contains an invalid source: ''wasm-eval''. It will be ignored.
spark_polymer.html:1 The source list for Content Security Policy directive 'script-src' contains an invalid source: ''wasm-eval''. It will be ignored.
```

**Comment by nightsky30** [comment]
I just found CDE and became interested in development for Chrome OS.  Won't work in Chrome 67 on Linux either :(

**Comment by darthwalsh** [comment]
Chrome Dev Editor was cool while it worked, but there's a few other tools you can try now:

If you have a new Chromebook and want to try some new dev-channel features, the new Linux app feature would let you use linux tools for web development: https://www.xda-developers.com/apollo-lake-chromebooks-acer-asus-lenovo-dell-linux-app/

One other way to develop on a Chromebook is to use the Android app support to run Termux through a bash emulator: https://blog.lessonslearned.org/building-a-more-secure-development-chromebook/

**Comment by nightsky30** [comment]
@darthwalsh 
Thank you for the suggestions.  So the app is not for me, but for another person who has a chromebook.  I have a normal PC running Linux.  I just want to develop for their chromebook, but develop on my Linux box.  I was looking at just doing Android app development because it seems that is where chomebooks are heading.

**Comment by rafi16jan** [comment]
@nightsky30 yeah you're better to develop Android Apps than Chrome Apps now, it will be deprecated in favor of Desktop PWA (but extensions still available). But if you're already know web development you should just start develop with PWA frameworks like Polymer, React, Vue, etc.. It works on every browser and OS or even you can put it on a WebView

**Comment by nightsky30** [comment]
@rafi16jan cool, thank you.  I'll try looking into PWAs instead.

**Comment by nmcain** [comment]
I have gotten it to run on windows with nw.js 0.25.4, which uses an older version of chromium from before the security update  that broke CDE. It works completely. I will upload a google drive link ASAP. While I am at it, I will try to fix that transparent menu. 

PS It works on crossover on Chrome OS

**Comment by rafi16jan** [comment]
@nmcain Android CrossOver or Linux CrossOver? And CrossOver only works on Intel based Chromebooks...

**Comment by jakcharvat** [comment]
@nmcain Hello. Could you please point me in the correct direction to where that to-be-deleted code is? I am on windows, so linux or chrome-os alternatives are not an option for me. Thanks

**Comment by nmcain** [comment]
Yeah it turns out it was not a code problem, it was the fact that it used inline scripts or something to violate the chrome security policy. But there were issues in the loading screen and the /deep/ combinator. Nw.js does run on windows, and I have packaged an installer for windows, If you want it I will put it here.

**Comment by jakcharvat** [comment]
Yes please @nmcain

**Comment by nmcain** [comment]
`https://drive.google.com/file/d/1prWZ8kGsy8BytTzsbyyuGLyE_B7Yf-r0/view?usp=sharing`

**Comment by jakcharvat** [comment]
Thank you!

**Comment by ijo-amali** [comment]
I'm on Chrome OS and I figured out a way to inspect an app. What code do I delete?

**Comment by nmcain** [comment]
No code really, I thought it was that issue, but it is actually the chrome security policy. On windows, I would recommend the Google drive Link I posted with an old build of nw.js

**Comment by ijo-amali** [comment]
Ah, I see. I guess there's no hope for Chrome OS users, then.

**Comment by luis-fonseca** [comment]
The application does not load. You have been in the charging screen for a long time.

**Comment by Eric-art-coder** [comment]
![image](https://user-images.githubusercontent.com/22538641/46933972-b5dba300-d088-11e8-9a68-68d43b3e5ad2.png)
always loading 
can auther fix it ?

**Comment by nmcain** [comment]
Unfortunately, no. It is no longer under development, you could fork it and attempt to fix all of the security issues yourself, but this has got to be the second most irritating code I have ever looked at.

**Comment by nmcain** [comment]
As soon as I finish my personal projects, (Or get bored), I will make an attempt to have it pass the content security policies.

**Comment by Eric-art-coder** [comment]
now i have to use Text editor my repo

**Comment by CryogenDev** [comment]
Hey guys, I may have found a fix. Maybe. 

`A Chrome extension needs to use the CSP compliant script. The CSP compliant scripts are automatically generated by pub build with the extension dart.precompiled. There is also an option 'csp: true' for the Polymer transformer which must be set when Polymer is used. There is also a transformer in the chrome.dart package which does this automatically on pub build.`

**Comment by nmcain** [comment]
That might work! CSP has changed a lot since v64, though.
